project:
  type: website

website:
  title: "gkrikor1.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



