project:
  type: website

website:
  title: "gkrikor1.github.io"
  description: "Greg Krikorian Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
    right:
     - icon: linkedin
     - href: www.linkedin.com/in/greg-krikorian


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



